version: '3.1'

services:

  database:
    build: 
      context: .
      dockerfile: mysqldb.dockerfile
    container_name: cont-mysql
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: usuarios
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - schemas:/var/lib/mysql
    networks:
      app-networks:
        aliases:
          - mysqldb_host
    restart: always

  backend:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: cont-php
    ports: 
      - 8181:80
    volumes:
      - ./www:/var/www/html
    depends_on:
      - database
    networks:
      app-networks:
        aliases:
          - php_host
    restart: always
  
  phpmyadmin:
    build: 
      context: .
      dockerfile: phpmyadmin.dockerfile
    container_name: cont-phpmyadmin
    depends_on:
      - database
    ports:
      - 8001:80
    environment:
      - PMA_HOST=database
    networks:
        app-networks:
          aliases:
            - phpmyadmin_host
    restart: always

volumes:
  www: {}
  schemas: 

networks:
  app-networks:
    name: web-networks
    driver: bridge #puente
    ipam: #administrador del direccionamiento
      driver: default 